export interface Module {
  id: number;
  name: string;
  category: Category;
  description: string;
  theory: string;
  difficulty?: 'beginner' | 'intermediate' | 'advanced';
  enhanced?: boolean;
}

export type Category = 'Mathematics' | 'Physics' | 'Chemistry' | 'Biology' | 'Engineering';

export const CATEGORIES: Category[] = ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'Engineering'];

export const MODULES: Module[] = [
  // ── MATHEMATICS ─────────────────────────────────────────────────────────────
  { id: 1, name: 'Algebra: Addition & Subtraction', category: 'Mathematics', difficulty: 'beginner', description: 'Balance a scale with X blocks and number weights', theory: 'Think of algebra like a seesaw! Both sides must always be equal. When we have "x + 3 = 7", we can remove 3 weights from each side to find x = 4.' },
  { id: 2, name: 'Algebra: Multiplication (Area Model)', category: 'Mathematics', difficulty: 'beginner', description: 'Watch a rectangle grow to show (x+a)(x+b)', theory: 'Multiplying two expressions is like finding the area of a rectangle! (x+2)(x+3) means one side is "x+2" long and the other is "x+3" long.' },
  { id: 3, name: 'Algebra: Division', category: 'Mathematics', difficulty: 'beginner', description: 'Slice a 3D volume into equal sections', theory: 'Division in algebra means splitting a big expression into equal groups.' },
  { id: 4, name: 'Factorizing', category: 'Mathematics', difficulty: 'intermediate', description: 'Break a block into its factor pieces', theory: 'Factorizing is like finding the building blocks of a number or expression.' },
  { id: 5, name: 'Expanding Expressions', category: 'Mathematics', difficulty: 'intermediate', description: 'Merge small volumes into a polynomial block', theory: 'Expanding is the OPPOSITE of factorizing.' },
  { id: 6, name: 'Slope & Linear Functions', category: 'Mathematics', difficulty: 'beginner', enhanced: true, description: 'Live graph sync, rolling ball, rise/run triangle overlay', theory: 'The slope "m" tells you how steep the line is. "c" is where the line crosses the y-axis. A rolling ball\'s speed is controlled by the steepness!' },
  { id: 7, name: 'Parabolas (Quadratic Functions)', category: 'Mathematics', difficulty: 'intermediate', enhanced: true, description: 'Vertex glow, X-intercept dashed lines, 3 scenario views', theory: 'Parabolas are U-shaped curves from y = ax² + bx + c. The vertex is the turning point. Roots are where it crosses y = 0.' },
  { id: 8, name: 'Systems of Equations', category: 'Mathematics', difficulty: 'intermediate', description: 'Two intersecting 3D planes with glowing intersection', theory: 'Two equations can be like two roads on a map. Where they cross is the ONE point that satisfies BOTH equations.' },
  { id: 9, name: 'The Unit Circle', category: 'Mathematics', difficulty: 'intermediate', description: 'A rotating wheel showing sin and cos bars', theory: 'The unit circle is a circle with radius 1. As a point travels around it, its height is the Sine and its sideways distance is the Cosine.' },
  { id: 10, name: 'Volume Relationships', category: 'Mathematics', difficulty: 'intermediate', description: 'Three cones fill one cylinder exactly', theory: '3 cones with the same base and height as a cylinder will fill it EXACTLY!' },
  { id: 11, name: 'Riemann Sums', category: 'Mathematics', difficulty: 'advanced', enhanced: true, description: 'Left/Right/Midpoint methods, exact vs estimated area, function chooser', theory: 'Fill a curve with rectangles. More rectangles = more accuracy. This is the foundation of integration!' },
  { id: 12, name: 'The Tangent Line', category: 'Mathematics', difficulty: 'advanced', description: 'A balancing plank showing slope at a single point', theory: 'The tangent line touches a curve at just ONE point. Its slope is the derivative!' },
  { id: 34, name: 'Matrix Transformations', category: 'Mathematics', difficulty: 'advanced', enhanced: true, description: 'Animated 3D cube transform, 3×3 matrix input, live determinant', theory: 'A matrix is a grid of numbers that transforms space! Multiplying a shape by a matrix rotates, scales, shears, or collapses it. The determinant tells you how much the volume changes.' },
  { id: 35, name: 'Cross Product of Vectors', category: 'Mathematics', difficulty: 'advanced', enhanced: true, description: '3D vectors A, B, C with right-hand rule, live computation steps', theory: 'The cross product of two vectors gives a THIRD vector perpendicular to both! Use the right-hand rule: point fingers along A, curl toward B, and your thumb points toward A × B.' },
  // ── PHYSICS ──────────────────────────────────────────────────────────────────
  { id: 13, name: 'Forces on an Incline', category: 'Physics', difficulty: 'intermediate', enhanced: true, description: 'Live force vectors, FBD chart, scenario switcher', theory: 'Three forces act on a block on a ramp: Gravity (down), Normal Force (away from surface), and Friction (opposing motion).' },
  { id: 14, name: 'Projectile Motion', category: 'Physics', difficulty: 'intermediate', enhanced: true, description: 'Multi-planet gravity, live trajectory + height charts', theory: 'Horizontal motion is constant; vertical motion is controlled by gravity. Different planets have different g!' },
  { id: 15, name: 'Displacement vs Distance', category: 'Physics', difficulty: 'beginner', description: 'Winding path vs straight-line shortcut arrow', theory: 'Distance is total path; displacement is straight-line start to finish.' },
  { id: 16, name: 'Centripetal Force', category: 'Physics', difficulty: 'intermediate', enhanced: true, description: 'Fc = mv²/r live formula, tension vector, snap-wire scenario', theory: 'Centripetal force pulls an orbiting object inward. F = mv²/r — faster spin or larger mass needs more force!' },
  { id: 17, name: 'Torque', category: 'Physics', difficulty: 'intermediate', description: 'A wrench showing how distance multiplies turning force', theory: 'Torque = Force × distance from pivot. A longer wrench needs less force for the same turning power!' },
  { id: 18, name: "Bernoulli's Principle", category: 'Physics', difficulty: 'intermediate', description: 'Narrowing pipe: particles speed up, pressure drops', theory: 'Fast flow = low pressure. This explains airplane lift!' },
  { id: 19, name: 'Electric Fields', category: 'Physics', difficulty: 'advanced', enhanced: true, description: 'Spawn charges, drag field probe, dipole/capacitor scenarios', theory: 'Charges create electric fields. Field lines show where a positive test charge would move.' },
  { id: 20, name: 'Circuit Flow', category: 'Physics', difficulty: 'intermediate', description: 'Electron spheres flowing through battery, wire, and bulb', theory: 'Electrons flow from negative to positive terminal. The battery pumps them around.' },
  { id: 21, name: 'Simple Harmonic Motion', category: 'Physics', difficulty: 'advanced', description: 'Pendulum painting a sine wave trail', theory: 'Back-and-forth motion traces a perfect sine wave over time.' },
  { id: 36, name: 'Special Relativity', category: 'Physics', difficulty: 'advanced', enhanced: true, description: 'Time dilation, Lorentz contraction, dual clocks, light-speed scenarios', theory: 'At near-light speeds, time slows down and objects shrink in the direction of travel! The faster you go, the more time "stretches" for you.' },
  // ── CHEMISTRY ────────────────────────────────────────────────────────────────
  { id: 22, name: 'Ionic Bonding', category: 'Chemistry', difficulty: 'intermediate', description: 'Electron jumps between atoms, ions attract', theory: 'One atom gives an electron to another. The giver becomes + and taker becomes −. They attract like magnets!' },
  { id: 23, name: 'Covalent Bonding', category: 'Chemistry', difficulty: 'intermediate', description: 'Two atoms share a glowing electron cloud', theory: 'Covalent bonds share electrons. Both atoms hold on like two kids sharing a toy.' },
  { id: 24, name: 'Balancing Equations', category: 'Chemistry', difficulty: 'intermediate', description: 'Lego-style molecules balanced on both sides', theory: 'Atoms cannot disappear. Count and match both sides!' },
  { id: 25, name: 'Molecular Geometry', category: 'Chemistry', difficulty: 'advanced', description: '3D bond shapes: tetrahedral, bent, linear', theory: 'Electron repulsion pushes bonds apart into 3D shapes. Shape controls chemical behavior!' },
  { id: 26, name: 'States of Matter', category: 'Chemistry', difficulty: 'beginner', description: 'Atoms: vibrate (solid), flow (liquid), zoom (gas)', theory: 'Adding heat gives particles more energy. At some temperature they break free!' },
  { id: 27, name: 'Atomic Orbitals', category: 'Chemistry', difficulty: 'advanced', description: 'Dumbbell and sphere electron probability clouds', theory: 'Electrons live in probability clouds called orbitals — s spheres and p dumbbells.' },
  // ── BIOLOGY ──────────────────────────────────────────────────────────────────
  { id: 28, name: 'The Animal Cell', category: 'Biology', difficulty: 'beginner', description: 'Clickable organelles: nucleus, mitochondria, ribosomes', theory: 'Nucleus = control center. Mitochondria = power plant. Click each organelle to learn its job!' },
  { id: 29, name: 'The Plant Cell', category: 'Biology', difficulty: 'beginner', description: 'Cell wall, vacuole, chloroplasts — click to label', theory: 'Plant cells have a stiff wall, green chloroplasts for photosynthesis, and a huge water vacuole.' },
  { id: 30, name: 'Plant Systems', category: 'Biology', difficulty: 'beginner', description: 'Water up xylem, sugar down phloem — live particles', theory: 'Xylem carries water up; phloem carries sugar down. Two pipe systems in every stem!' },
  { id: 31, name: 'Human Body Systems', category: 'Biology', difficulty: 'beginner', description: 'Toggle skeletal, circulatory, digestive systems', theory: 'Skeletal = frame, Circulatory = delivery, Digestive = fuel processor. All work together!' },
  { id: 32, name: 'DNA Double Helix', category: 'Biology', difficulty: 'intermediate', description: 'Twisting ladder that unzips for replication', theory: 'DNA is a twisted ladder. The rungs are A-T and C-G base pairs. Unzip to copy!' },
  { id: 33, name: 'Plate Tectonics', category: 'Biology', difficulty: 'intermediate', description: 'Subduction: one plate dives under, volcano erupts', theory: 'Earth\'s plates float on hot rock. Collision → subduction → volcano eruption!' },
  // ── ENGINEERING ──────────────────────────────────────────────────────────────
  { id: 37, name: 'Stress vs. Strain (Tensile Testing)', category: 'Engineering', difficulty: 'intermediate', enhanced: true, description: 'Stretch a material to failure, live stress-strain curve with yield point', theory: 'Stress = force / area. Strain = extension / original length. Every material has an elastic limit — beyond it, permanent deformation occurs!' },
  { id: 38, name: 'PID Controller (Drone Hover)', category: 'Engineering', difficulty: 'advanced', enhanced: true, description: 'Tune P/I/D gains, see drone overshoot/oscillate/stabilize live', theory: 'A PID controller corrects errors using: Proportional (current error), Integral (accumulated error), Derivative (rate of change). Perfect tuning = smooth, fast response!' },
  { id: 39, name: 'Aerodynamic Lift (Airfoil)', category: 'Engineering', difficulty: 'intermediate', enhanced: true, description: 'Wind tunnel with flow lines, stall detection, Lift vs Drag chart', theory: 'An airfoil\'s curved top makes air travel faster, creating lower pressure above = lift! At high angles of attack, the flow separates — this is a stall!' },
  { id: 40, name: 'Gear Ratios & Mechanical Advantage', category: 'Engineering', difficulty: 'intermediate', enhanced: true, description: 'Meshed 3D gears, spin with mouse, RPM and torque readouts', theory: 'Gear ratio = teeth on output / teeth on input. More teeth on output = more torque but slower speed. That\'s mechanical advantage!' },
  // ── MATHEMATICS (Batch 3) ────────────────────────────────────────────────────
  { id: 41, name: '3D Coordinate Systems', category: 'Mathematics', difficulty: 'intermediate', enhanced: true, description: 'Switch between Cartesian, Spherical, and Cylindrical coordinate systems with live conversion', theory: 'A single point in space can be described in three different ways. Cartesian uses (x,y,z) boxes, Spherical uses (r,θ,φ) angles and radius, Cylindrical mixes both approaches.' },
  { id: 42, name: 'Fourier Series Approximation', category: 'Mathematics', difficulty: 'advanced', enhanced: true, description: 'Spinning epicycles build square and sawtooth waves, live frequency spectrum', theory: 'Any repeating wave can be built from spinning circles (harmonics)! Adding more circles adds higher frequencies, making the approximation more accurate — this is the foundation of signal processing.' },
  { id: 43, name: 'Eigenvalues & Eigenvectors', category: 'Mathematics', difficulty: 'advanced', enhanced: true, description: '2×2 matrix warps space, eigenvectors glow when they survive unchanged in direction', theory: 'When a matrix transforms space, most vectors change direction. Eigenvectors are special — they only scale, never rotate! Their scale factor is the eigenvalue.' },
  // ── PHYSICS (Batch 4) ────────────────────────────────────────────────────────
  { id: 44, name: 'Doppler Effect', category: 'Physics', difficulty: 'intermediate', enhanced: true, description: 'Moving source compresses/stretches sound waves, Mach cone at supersonic speeds', theory: 'A moving sound source squashes waves in front and stretches them behind. You hear a higher pitch approaching and lower pitch receding. At supersonic speed, waves pile into a shock cone!' },
  { id: 45, name: 'Wave Interference (Double Slit)', category: 'Physics', difficulty: 'advanced', enhanced: true, description: 'Two wave sources create interference patterns, intensity projected on back wall', theory: 'Two wave sources create overlapping ripples. Where crests meet crests, waves reinforce (constructive). Where crests meet troughs, they cancel (destructive) — creating a striped pattern.' },
  { id: 46, name: 'Lorentz Force', category: 'Physics', difficulty: 'advanced', enhanced: true, description: 'Charged particle curves in magnetic field, F = q(v × B) live readout', theory: 'A charged particle moving through a magnetic field experiences a force perpendicular to both its velocity and the field. This curves the path into a circle — this is how particle accelerators work!' },
  { id: 47, name: "Kepler's Second Law", category: 'Physics', difficulty: 'intermediate', enhanced: true, description: 'Planet sweeps equal areas in equal times, velocity peaks at perihelion', theory: 'A planet moves faster when closer to the star and slower when far away — but always sweeps the same area per unit time. This is conservation of angular momentum in action.' },
  { id: 48, name: 'Truss Bridge Load Distribution', category: 'Engineering', difficulty: 'advanced', enhanced: true, description: 'Warren/Pratt truss beams glow red (compression) or blue (tension) under load', theory: 'Trusses distribute loads through triangles. Top members are compressed, bottom members are in tension. Engineers choose truss shape to match the expected load pattern.' },
  { id: 49, name: 'Logic Gates', category: 'Engineering', difficulty: 'beginner', enhanced: true, description: 'Toggle inputs A/B, watch logic paths light up, truth table updates live', theory: 'Logic gates are the building blocks of computers! AND needs both inputs true. OR needs one. XOR means "exclusive or" — different inputs. NAND is the universal gate you can build anything from.' },
  { id: 50, name: 'Fluid Dynamics (Reynolds Number)', category: 'Physics', difficulty: 'intermediate', enhanced: true, description: 'Laminar smooth flow transitions to turbulent chaos as Re increases', theory: 'At low Reynolds numbers, fluid flows in neat parallel layers (laminar). Above ~4000, flow becomes chaotic and turbulent. Re = ρvD/μ — inertial forces vs viscous forces.' },
  { id: 51, name: 'Thermodynamic Cycles', category: 'Physics', difficulty: 'advanced', enhanced: true, description: 'Carnot/Otto cycle piston with P-V loop chart, gas particles change color with temperature', theory: 'Heat engines convert thermal energy to work by cycling a gas through compression and expansion. The P-V diagram area equals the net work done per cycle — that\'s the engine\'s power output.' },
  { id: 52, name: 'Doppler Radar & Signal Modulation', category: 'Engineering', difficulty: 'advanced', enhanced: true, description: 'AM vs FM wave modulation with time-domain and frequency-domain plots', theory: 'AM modulation changes wave amplitude to encode information. FM modulation changes frequency instead — more noise-resistant. Your car radio uses both! The frequency domain reveals the hidden sidebands.' },
  { id: 53, name: 'Gyroscopic Precession', category: 'Physics', difficulty: 'advanced', enhanced: true, description: 'Spinning flywheel precesses perpendicular to applied torque, angular momentum visualization', theory: 'When you push down on a spinning gyroscope, it doesn\'t fall — it rotates sideways! Gyroscopic precession occurs because angular momentum must be conserved. This is why bikes stay upright!' },
  { id: 54, name: 'Cantilever Beam Deflection', category: 'Engineering', difficulty: 'intermediate', enhanced: true, description: 'Beam bends under tip load, stress color map from green to red', theory: 'A cantilever beam fixed at one end deflects under load. Maximum stress is at the fixed end. δ = FL³/3EI — deflection depends on force, length cubed, and material stiffness.' },
  { id: 55, name: 'Electrical Transformer', category: 'Engineering', difficulty: 'intermediate', enhanced: true, description: 'Primary/secondary coil turns control voltage step-up or step-down, flux animation', theory: 'A transformer changes AC voltage using magnetic induction. More turns on the secondary side steps voltage up; fewer steps it down. V2/V1 = N2/N1 — the turns ratio is everything.' },
  // ── CHEMISTRY (Batch 5) ──────────────────────────────────────────────────────
  { id: 56, name: "Le Chatelier's Principle", category: 'Chemistry', difficulty: 'advanced', enhanced: true, description: 'Adjust pressure/temperature/concentration, watch equilibrium shift in real-time', theory: "If you disturb a chemical equilibrium, the system shifts to counteract the change. Increase pressure? Reaction favors the side with fewer gas molecules. Increase temperature? Favors the endothermic direction." },
  { id: 57, name: 'Acid-Base Titration', category: 'Chemistry', difficulty: 'intermediate', enhanced: true, description: 'Drip acid/base from burette, sharp pH color change at equivalence point', theory: 'Titration adds a known concentration of acid or base to neutralize an unknown. The equivalence point is where moles match exactly. The pH curve spikes sharply at this moment — detect it with an indicator dye.' },
  { id: 58, name: 'Galvanic Cell (Electrochemistry)', category: 'Chemistry', difficulty: 'advanced', enhanced: true, description: 'Metal dissolves at anode, plates at cathode, live voltage from standard reduction potentials', theory: 'A galvanic cell converts chemical energy to electricity. Oxidation at the anode loses electrons; reduction at the cathode gains them. The voltage depends on which metals you choose.' },
  { id: 59, name: 'Radioactive Decay & Half-Life', category: 'Chemistry', difficulty: 'intermediate', enhanced: true, description: '100 atoms randomly decay over time, exponential decay curve plots live', theory: 'Radioactive atoms decay randomly, but in bulk they follow a predictable exponential pattern. After one half-life, half remain. After two, a quarter. N = N₀ × (½)^(t/t½)' },
  { id: 60, name: 'Enzyme-Substrate Kinetics', category: 'Chemistry', difficulty: 'advanced', enhanced: true, description: 'Lock-and-key model deforms when pH/temperature deviates, reaction rate peaks at optimum', theory: 'Enzymes work like locks — only the right-shaped substrate fits. Too hot or wrong pH distorts the enzyme\'s active site, stopping the reaction. This is why body temperature matters so precisely.' },
  // ── BIOLOGY (Batch 6) ────────────────────────────────────────────────────────
  { id: 61, name: 'Mitosis (Cell Division)', category: 'Biology', difficulty: 'intermediate', enhanced: true, description: 'Phase slider: chromosomes condense, align, separate, and pinch into two cells', theory: 'Mitosis creates two identical daughter cells. Chromosomes first copy (S phase), then condense, line up at the equator, get pulled apart by spindle fibers, and the cell divides — giving each daughter a full set.' },
  { id: 62, name: 'Synaptic Nerve Impulse', category: 'Biology', difficulty: 'advanced', enhanced: true, description: 'Action potential fires neurotransmitters across synapse gap, calcium ion graph', theory: 'When an electrical signal reaches a nerve terminal, calcium rushes in. This triggers vesicles to release neurotransmitters across the synapse gap. They bind to receptors and continue the signal.' },
  { id: 63, name: 'The Carbon Cycle', category: 'Biology', difficulty: 'intermediate', enhanced: true, description: 'Carbon nodes flow between ocean, trees, and atmosphere; PPM counter rises with emissions', theory: 'Carbon constantly cycles: plants absorb it via photosynthesis, animals release it by breathing, oceans dissolve it, and volcanoes emit it. Human emissions add extra carbon, raising atmospheric CO₂.' },
  { id: 64, name: 'Nephron Filtration (Kidney)', category: 'Biology', difficulty: 'advanced', enhanced: true, description: 'Blood pressure drives filtration, GFR calculation, waste vs blood cell separation', theory: 'The nephron is the kidney\'s filter unit. High blood pressure in the glomerulus pushes water and small molecules out, while keeping large cells and proteins in. About 180L of filtrate is made daily!' },
  { id: 65, name: 'Action Potential (Neuron)', category: 'Biology', difficulty: 'advanced', enhanced: true, description: 'Stimulus opens Na⁺ channels then K⁺ channels, classic mV spike drawn live', theory: 'When a neuron is stimulated enough, sodium channels snap open, causing a rapid voltage spike (+40mV). Potassium channels then open to repolarize. The whole event takes just 2 milliseconds.' },
  { id: 66, name: 'Glacial Retreat & Albedo Feedback', category: 'Biology', difficulty: 'intermediate', enhanced: true, description: 'Ice shrinks with temperature, albedo drops, feedback loop accelerates warming', theory: 'Ice reflects 90% of sunlight (high albedo). As it melts, dark ocean absorbs 94% instead. This extra heat melts more ice — a positive feedback loop that accelerates climate change.' },
  { id: 67, name: 'Antibiotic Resistance Evolution', category: 'Biology', difficulty: 'intermediate', enhanced: true, description: 'Petri dish: antibiotic kills green bacteria, resistant orange bacteria multiply to fill dish', theory: 'When antibiotics kill most bacteria, resistant mutants survive and reproduce. This is natural selection in real time! The bacteria aren\'t "learning" — the weak ones die and the strong ones inherit the dish.' },
  { id: 68, name: 'Oceanic Thermohaline Circulation', category: 'Biology', difficulty: 'intermediate', enhanced: true, description: 'Freshwater melt slows circulation ribbons, salinity-density chart drives conveyor', theory: 'Ocean currents are driven by differences in water density. Cold salty water sinks near the poles, pulling warm surface water north. Adding freshwater from melting ice lowers density, potentially stopping this conveyor.' },
  { id: 69, name: 'Photosynthesis (Light Reactions)', category: 'Biology', difficulty: 'intermediate', enhanced: true, description: 'Photons split water in thylakoid, ATP and NADPH production rate chart', theory: 'In the light reactions, photons energize electrons in chlorophyll. These electrons split water molecules, releasing oxygen. The energy is stored in ATP and NADPH — the fuel for building sugar in the Calvin cycle.' },
  { id: 70, name: '3D Printing & G-Code Layering', category: 'Engineering', difficulty: 'beginner', enhanced: true, description: 'Simulated nozzle deposits layers, infill pattern selector, print time estimate', theory: 'A 3D printer reads G-code — coordinates telling the nozzle where to move. It builds objects layer by layer. Infill density (the internal structure) trades weight for strength. More layers = finer detail but longer print time.' },
];
